# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Stephen Chapman
tagline:             'Personal website'
description:         'A personal website for Stephen Chapman'
url:                 http://stephenchapman.me
baseurl:             ''
paginate:            1
remote_theme: "mmistakes/minimal-mistakes"

# About/contact
author:
  name:              Stephen
  url:               https://twitter.com/stephenchapman
  email:             stevochapman@gmail.com

# Custom vars
version:             1.0.0